.PHONY: clean help new-screen

# Default target
help:
	@echo "Available commands:"
	@echo "  make new-screen          - Create a new screen (interactive)"
	@echo "  make new-screen NAME=Foo - Create a new screen named Foo"
	@echo "  make new-screen NAME=Foo SHADER=yes - With Metal shader"
	@echo "  make clean               - Remove build artifacts"
	@echo ""
	@echo "Note: Metal shaders and ScreenID.swift are automatically"
	@echo "      generated by SPM plugins during build."

# Create a new screen
new-screen:
ifdef NAME
ifdef SHADER
	@./Scripts/new_screen.sh $(NAME) --shader
else
	@./Scripts/new_screen.sh $(NAME)
endif
else
	@./Scripts/new_screen.sh
endif

# Clean build artifacts
clean:
	@echo "🧹 Cleaning build artifacts..."
	@rm -rf ~/Library/Developer/Xcode/DerivedData/MyToybox-*
	@rm -rf Packages/.build
	@echo "✅ Clean complete"
