.PHONY: clean help

# Default target
help:
	@echo "Available commands:"
	@echo "  make clean - Remove build artifacts"
	@echo ""
	@echo "Note: Metal shaders and ScreenID.swift are automatically"
	@echo "      generated by SPM plugins during build."

# Clean build artifacts
clean:
	@echo "🧹 Cleaning build artifacts..."
	@rm -rf ~/Library/Developer/Xcode/DerivedData/MyToybox-*
	@rm -rf Packages/.build
	@echo "✅ Clean complete"

