@_exported import MetadatasMacros
@_exported import MyToyboxCore

/// Re-export @Metadata macro with ScreenMetadata conformance.
///
/// This redefinition adds `conformances: ScreenMetadata` which is required
/// for the Swift compiler to recognize the protocol conformance generated by the macro.
/// The original macro in MetadatasMacros cannot reference ScreenMetadata directly
/// because it's defined in MyToyboxCore.
@attached(extension, conformances: ScreenMetadata, names: named(title), named(description), named(tags))
public macro Metadata(
    title: String,
    description: String,
    tags: [Tag]
) = #externalMacro(module: "MetadatasMacrosImpl", type: "MetadataMacro")
