extension ScreenID: Identifiable {
    var id: String {
        rawValue
    }
}

enum ScreenID: String, Codable, CaseIterable {
    case gradientPolygon
    case collisionColorChange
    case solarSystemAnimationView
    case pixelBasedColorToggleView
    case heliocentricAnimationView
    case countdownAnimation
    case infinitescroll
    case horizontalPicker
    case circleSDF1
    case circleSDF2
    case wavingText
    case coloredMap
    case monotoneMap
    case waveParticle
    case reverseList
    case viewIdentity
    case progressiveblur
    case shaderMosaic
    case shaderTile
    case shaderSpiral
    case primeSpiral
    case archimedesSpiral
    case motions4
    case matchTopWidth
    case authCode
    case tileAnimation3D
    case tileAnimation
    case shineShader
    case waveCircle
    case rectangleAnimation
    case dateformatstyle
    case scaledmetric
    case dynamictype
    case colorSchemeAnimation
    case uiviewcontrollerrepresentable
    case enumpicker
    case ringSlider
    case unevenRoundedRectang1
    case unevenRoundedRectang2
    case colorHexAnimation
    case swiftuiglowtext
    case ringanimation
    case progressring
    case button
    case lostRowAnimation
    case swiftuiwalletcardtransition
    case hierarchicalShapeStyle
    case uicollectionlayoutlistconfiguration
    case uitableviewpractice
    case mazeGenerator
    case meshgradient
    case visualeffect
    case contenttransition
    case flowlayout
    case viewLayout
    case hackertexteffectswiftuiios16Ios17
    case y
    case gradientAnimationView
    case editmodesample
    case juliasetview
    case squreflowview
    case smoothmin2d
    case customloadinganimation2
    case customloadinganimation
    case homeIconShakeView
    case customanimation
    case loadingAnimationView1
    case loadingAnimationView2
    case loadingAnimationView3
    case segmentedControlView
    case metaball
    case localizeddateformat
    case zip3
    case semanticversion
    case userdefaultsclient
    case preferencesCgsizeViewmodifier
    case swiftuiView
    case dynamicpropertyUideviceorientation
    case swiftuiSwinject
    case asyncQueueComparisonView
    case dataRaceDemoView
    case stateobjectWrappedvalue
    case observableobject
    case swiftuiStateobject
    case playstationlogo
    case applelogo
    case asyncstreamwrapper
    case uitableview
    case withthrowingtaskgroup
    case timerasyncstream
    case stopwatchswift
    case dataScienceIntroView
    case easinganimationview
    case optionalcollection
    case dynamicprogramming21view
    case dynamicprogramming15view
    case dynamicprogramming14view
    case dynamicprogramming13view
    case anyrawvaluesenum
    case datasourceCellprovider
    case uicollectionview
    case nslayoutconstraintactivate
    case animatablevector
    case memoize
    case laobject
    case result
    case either
    case splitsignalsignalproducer
    case readalargetextfilelinebylineswift3
}
