extension ScreenID: Identifiable {
    var id: String {
        rawValue
    }
}

enum ScreenID: String, Codable, CaseIterable {
    case gradientPolygon
    case collisionColorChange
    case solarSystemAnimationView
    case pixelBasedColorToggleView
    case heliocentricAnimationView
    case countdownAnimation
    case infinitescrollview
    case horizontalpickerview
    case circlesdf2view
    case circlesdfview
    case wavingtextview
    case typingtextview
    case colornavigationview
    case colornavigation
    case coloredMapView
    case monotonemap
    case msl
    case reverseListView
    case viewIdentity
    case progressiveblur
    case shaderMosaicView
    case shaderTileView
    case shaderSpiralView
    case primeSpiralView
    case archimedesSpiralView
    case tasksleep
    case motions
    case hstackView
    case ui
    case animation2
    case modifier
    case swingAnimationView
    case glslMsl
    case waveAnimationView
    case rectangleAnimationView
    case dateformatstyle
    case uikitdatepicker
    case dynamicTypeScalingView
    case scaledmetricDynamictypesize
    case appearanceModeAnimationView
    case uiviewcontrollerrepresentable
    case enumpicker
    case ringslider
    case unevenroundedrectanglesample2
    case unevenroundedrectanglesample
    case coloranimation
    case swiftuiglowtext
    case ringanimation
    case progressring
    case button
    case scrollviewlazyvstack
    case swiftuiwalletcardtransition
    case hierarchicalshapestyle
    case uicollectionlayoutlistconfiguration
    case uitableviewpractice
    case aldousbroderalgorithm
    case meshgradient2
    case meshgradient
    case visualeffect2
    case visualeffect
    case contenttransition
    case flowlayout
    case viewLayout
    case hackertexteffectswiftuiios16Ios17
    case y
    case gradientAnimationView
    case editmodesample
    case juliasetview
    case squreflowview
    case smoothmin2d
    case customloadinganimation2
    case customloadinganimation
    case homeIconShakeView
    case customanimation
    case loadingAnimationView1
    case loadingAnimationView2
    case loadingAnimationView3
    case segmentedControlView
    case metaball
    case localizeddateformat
    case zip3
    case semanticversion
    case userdefaultsclient
    case preferencesCgsizeViewmodifier
    case swiftuiView
    case dynamicpropertyUideviceorientation
    case swiftuiSwinject
    case asyncQueueComparisonView
    case dataRaceDemoView
    case stateobjectWrappedvalue
    case observableobject
    case swiftuiStateobject
    case playstationlogo
    case applelogo
    case asyncstreamwrapper
    case uitableview
    case withthrowingtaskgroup
    case timerasyncstream
    case stopwatchswift
    case dataScienceIntroView
    case easinganimationview
    case optionalcollection
    case dynamicprogramming21view
    case dynamicprogramming15view
    case dynamicprogramming14view
    case dynamicprogramming13view
    case anyrawvaluesenum
    case datasourceCellprovider
    case uicollectionview
    case nslayoutconstraintactivate
    case animatablevector
    case memoize
    case laobject
    case result
    case either
    case splitsignalsignalproducer
    case readalargetextfilelinebylineswift3
}
