import MyToyboxCore
import SwiftUI

// MARK: - MazeGeneratorScreen

/// A SwiftUI view that displays a maze generated by `MazeGeneratorViewModel` and allows the user to reset it.
@Metadata(title: .screenMazeGeneratorTitle, description: .screenMazeGeneratorDescription, tags: [])
public struct MazeGeneratorScreen: View {
    public init() {}

    /// The MazeGeneratorViewModel that manages the maze generation and state.
    /// 迷路の生成と状態を管理するための MazeGeneratorViewModel。
    @State private var viewModel = MazeGeneratorViewModel(width: 40, height: 40)

    /// An identifier used to refresh the maze generation task.
    /// 迷路生成タスクをリフレッシュするための識別子。
    @State private var viewID = UUID()

    public var body: some View {
        VStack {
            Spacer(minLength: 0)
            mazeGrid
            Spacer(minLength: 0)
            resetButton
        }
        .padding()
    }

    /// A grid that visualizes the maze based on the ViewModel's grid data.
    /// ViewModel の迷路データをグリッド状に可視化したビューです。
    var mazeGrid: some View {
        Grid(alignment: .center, horizontalSpacing: 0, verticalSpacing: 0) {
            ForEach(0 ..< viewModel.tiles.count, id: \.self) { i in
                GridRow(alignment: .center) {
                    ForEach(0 ..< viewModel.tiles[i].count, id: \.self) { j in
                        MazeTileView(tile: viewModel.tiles[i][j])
                    }
                }
            }
        }
        .task(id: viewID) {
            // Trigger the maze generation whenever viewID changes.
            // viewID が変更されるたびに迷路生成をトリガーします。
            await viewModel.generate()
        }
        .scaledToFit()
    }

    /// A button that resets the maze generation.
    /// 迷路の生成をリセットするためのボタンです。
    var resetButton: some View {
        Button {
            // Update viewID to force a new generation task.
            // 新しい生成タスクを起動するため、viewID を更新します。
            viewID = .init()
        } label: {
            Text(verbatim: "Reset")
        }
        .font(.title2)
        .fontWeight(.semibold)
        // Disable the button while the maze is generating.
        // 迷路生成中はボタンを無効化します。
        .disabled(viewModel.isGenerating)
    }
}

// MARK: - MazeTileView

struct MazeTileView: View {
    var tile: MazeTile

    var body: some View {
        Rectangle()
            .foregroundStyle(shapeStyle)
    }

    private var shapeStyle: some ShapeStyle {
        switch tile {
        case .start:
            AnyShapeStyle(.red)

        case .path:
            AnyShapeStyle(.foreground)

        case .wall:
            AnyShapeStyle(.background)

        case .goal:
            AnyShapeStyle(.green)
        }
    }
}

// MARK: - Preview

#Preview {
    MazeGeneratorScreen()
}
