extension ScreenID: Identifiable {
    var id: String {
        rawValue
    }
}

enum ScreenID: String, Codable, CaseIterable {
    case strokeModifier
    case capsule
    case metaball2D
    case lissajousCurve1
    case lissajousCurve2
    case gameOfLife
    case pipCard
    case voronoi
    case voronoi2
    case cosmicWeb
    case autoScrolledTextField
    case autoScrolledTextField2
    case flipTransition
    case spiralLayout
    case radialLayout
    case implicitEquation
    case flowDistortion
    case multiHelix
    case gradientPolygon
    case collisionColorChange
    case solarSystemAnimationView
    case pixelBasedColorToggleView
    case heliocentricAnimationView
    case countdownAnimation
    case infinitescroll
    case horizontalPicker
    case circleSDF1
    case circleSDF2
    case wavingText
    case coloredMap
    case monotoneMap
    case waveParticle
    case reverseList
    case viewIdentity
    case progressiveblur
    case shaderKuwahara
    case shaderMosaic
    case shaderTile
    case shaderSpiral
    case primeSpiral
    case archimedesSpiral
    case motions4
    case matchTopWidth
    case authCode
    case tileAnimation3D
    case tileAnimation
    case shineShader
    case waveCircle
    case rectangleAnimation
    case dateformatstyle
    case scaledmetric
    case dynamictype
    case colorSchemeAnimation
    case uiviewcontrollerrepresentable
    case enumpicker
    case ringSlider
    case unevenRoundedRectang1
    case unevenRoundedRectang2
    case colorHexAnimation
    case swiftuiglowtext
    case ringanimation
    case progressring
    case button
    case lostRowAnimation
    case swiftuiwalletcardtransition
    case hierarchicalShapeStyle
    case uicollectionlayoutlistconfiguration
    case uitableviewpractice
    case mazeGenerator
    case meshgradient
    case visualeffect
    case contentTransition
    case flowLayout
    case layoutProtocolSample
    case scrollRotation
    case gradientAnimation
    case juliaSet
    case squreflow
    case smoothMin
    case loadingAnimation1
    case loadingAnimation2
    case homeIconShakeView
    case customanimation
    case loadingAnimationView1
    case loadingAnimationView2
    case loadingAnimationView3
    case segmentedControl
    case applelogo
}
