#!/bin/bash
#
# Script to auto-generate ScreenID.swift from Screens.json
#
# Usage:
#   ./Scripts/generate_screen_id.sh
#
#
# Usage in an Xcode Build Phase:
#   1. Target > Build Phases > + > New Run Script Phase
#   2. Put the following in the script:
#        "${SRCROOT}/Scripts/generate_screen_id.sh"
#   3. Add to Input Files:
#        $(SRCROOT)/MyToybox/Resources/Screens.json
#   4. Add to Output Files:
#        $(SRCROOT)/MyToybox/Sources/Generated/ScreenID.swift
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SCREENS_JSON_FILE="$PROJECT_ROOT/MyToybox/Resources/Screens.json"
SCREEN_ID_FILE="$PROJECT_ROOT/MyToybox/Sources/Generated/ScreenID.swift"

# Extract ids from Screens.json
IDS=$(grep '"id":' "$SCREENS_JSON_FILE" | sed 's/.*"id": "\([^"]*\)".*/\1/')

# Validate that each id can be used as a Swift enum case name.
# - Must be a valid Swift identifier: ^[a-zA-Z_][a-zA-Z0-9_]*$
validate_identifier() {
    local id="$1"

    if [[ ! "$id" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
        echo "❌ Error: Invalid screen id for Swift identifier: \"$id\"" >&2
        echo "   - id must match: ^[a-zA-Z_][a-zA-Z0-9_]*$" >&2
        echo "   - example: gameOfLifeScreen, appleLogoScreen" >&2
        exit 1
    fi
}

# Generate case declarations
CASES=""
while IFS= read -r id; do
    validate_identifier "$id"
    CASES="${CASES}    case ${id}\n"
done <<< "$IDS"

# Remove the trailing newline
CASES=$(echo -e "$CASES" | sed '$ s/\\n$//')

# Generate ScreenID.swift
cat > "$SCREEN_ID_FILE" << 'HEADER'
// ⚠️ This file is auto-generated. Do not edit this file directly.
// Generated by: Scripts/generate_screen_id.sh
// Data source: MyToybox/Resources/Screens.json
//
import ScreenMacros
import SwiftUI

extension ScreenID: Identifiable {
    var id: String {
        rawValue
    }
}

// MARK: - ScreenID

/// Enum that identifies each sample screen.
///
/// The `@Screens` macro automatically generates `View` conformance and a `body` property.
/// Each case name is converted to UpperCamelCase and used as a View type.
///
/// Example: `case gameOfLifeScreen` → `GameOfLifeScreen()`
@Screens
enum ScreenID: String, Codable, CaseIterable {
HEADER

# Append cases
echo -e "$CASES" >> "$SCREEN_ID_FILE"

# Append closing brace
echo "}" >> "$SCREEN_ID_FILE"

# Print result
SCREEN_COUNT=$(echo "$IDS" | wc -l | tr -d ' ')
echo "✅ Generated ScreenID.swift ($SCREEN_COUNT screens)"


