#!/bin/bash
#
# Script to auto-generate ScreenID.swift from Screens.json
#
# Usage:
#   ./Scripts/generate_screen_id.sh                       # デフォルト設定で実行
#   ./Scripts/generate_screen_id.sh -i INPUT -o OUTPUT    # カスタム設定で実行
#
# オプション:
#   -i INPUT_FILE   入力ファイル（Screens.json）
#   -o OUTPUT_FILE  出力ファイル（ScreenID.swift）
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# デフォルト値
SCREENS_JSON_FILE=""
SCREEN_ID_FILE=""

# 引数解析
while getopts "i:o:" opt; do
    case $opt in
        i) SCREENS_JSON_FILE="$OPTARG" ;;
        o) SCREEN_ID_FILE="$OPTARG" ;;
        *) echo "Usage: $0 [-i INPUT_FILE] [-o OUTPUT_FILE]" && exit 1 ;;
    esac
done

# デフォルト値を設定（引数がない場合）
if [ -z "$SCREENS_JSON_FILE" ]; then
    SCREENS_JSON_FILE="$PROJECT_ROOT/App/MyToybox/Resources/Screens.json"
fi

if [ -z "$SCREEN_ID_FILE" ]; then
    SCREEN_ID_FILE="$PROJECT_ROOT/Packages/Sources/MyToyboxScreens/Generated/ScreenID.swift"
fi

# Extract ids from Screens.json
IDS=$(grep '"id":' "$SCREENS_JSON_FILE" | sed 's/.*"id": "\([^"]*\)".*/\1/')

# Validate that each id can be used as a Swift enum case name.
# - Must be a valid Swift identifier: ^[a-zA-Z_][a-zA-Z0-9_]*$
validate_identifier() {
    local id="$1"

    if [[ ! "$id" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
        echo "❌ Error: Invalid screen id for Swift identifier: \"$id\"" >&2
        echo "   - id must match: ^[a-zA-Z_][a-zA-Z0-9_]*$" >&2
        echo "   - example: gameOfLifeScreen, appleLogoScreen" >&2
        exit 1
    fi
}

# Generate case declarations
CASES=""
while IFS= read -r id; do
    validate_identifier "$id"
    CASES="${CASES}    case ${id}\n"
done <<< "$IDS"

# Remove the trailing newline
CASES=$(echo -e "$CASES" | sed '$ s/\\n$//')

# 出力ディレクトリを作成
mkdir -p "$(dirname "$SCREEN_ID_FILE")"

# Generate ScreenID.swift
cat > "$SCREEN_ID_FILE" << 'HEADER'
// ⚠️ This file is auto-generated. Do not edit this file directly.
//
// Generated by: Scripts/generate_screen_id.sh
// Data source: App/MyToybox/Resources/Screens.json
//
import ScreenMacros
import SwiftUI

extension ScreenID: Identifiable {
    var id: String {
        rawValue
    }
}

// MARK: - ScreenID

/// Enum that identifies each sample screen.
///
/// ## Overview
///
/// This file is **auto-generated** by an SPM Build Tool Plugin during the build process.
/// You should not edit this file directly. Instead, modify the source data.
///
/// ## Generation Process
///
/// 1. **Input**: `App/MyToybox/Resources/Screens.json`
///    - Contains screen metadata (id, title, description, tags)
/// 2. **Plugin**: `Packages/Plugins/GenerateScreenID/plugin.swift`
///    - SPM Build Tool Plugin that triggers generation
/// 3. **Script**: `Scripts/generate_screen_id.sh`
///    - Reads JSON, validates IDs, generates this Swift file
/// 4. **Output**: This file (`.build/plugins/outputs/.../ScreenID.swift`)
///    - SPM automatically includes plugin outputs in compilation
///
/// ## How It Works
///
/// The `@Screens` macro from [ScreenMacros](https://github.com/Koshimizu-Takehito/ScreenMacros)
/// generates `View` conformance. Each case name is converted to UpperCamelCase
/// and instantiated as the corresponding View type.
///
/// ```swift
/// case gameOfLifeScreen  →  GameOfLifeScreen()
/// case flowDistortionScreen  →  FlowDistortionScreen()
/// ```
///
/// ## Adding a New Screen
///
/// 1. Add a new entry to `Screens.json` with a unique `id`
/// 2. Create a corresponding View in `Packages/Sources/MyToyboxScreens/Screens/`
/// 3. Build the project - this file regenerates automatically
///
@Screens
enum ScreenID: String, Codable, CaseIterable, Sendable {
HEADER

# Append cases
echo -e "$CASES" >> "$SCREEN_ID_FILE"

# Append closing brace
echo "}" >> "$SCREEN_ID_FILE"

# Print result
SCREEN_COUNT=$(echo "$IDS" | wc -l | tr -d ' ')
echo "✅ Generated ScreenID.swift ($SCREEN_COUNT screens)"
echo "   Source: $(basename "$SCREENS_JSON_FILE")"
echo "   Output: $SCREEN_ID_FILE"
