#!/bin/bash
#
# Script to auto-generate Screen.swift from Screens.json
#
# Usage:
#   ./Scripts/generate_screen_id.sh                       # Run with default settings
#   ./Scripts/generate_screen_id.sh -i INPUT -o OUTPUT    # Run with custom settings
#
# Options:
#   -i INPUT_FILE   Input file (Screens.json)
#   -o OUTPUT_FILE  Output file (Screen.swift)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Default values
SCREENS_JSON_FILE=""
SCREEN_ID_FILE=""

# Parse arguments
while getopts "i:o:" opt; do
    case $opt in
        i) SCREENS_JSON_FILE="$OPTARG" ;;
        o) SCREEN_ID_FILE="$OPTARG" ;;
        *) echo "Usage: $0 [-i INPUT_FILE] [-o OUTPUT_FILE]" && exit 1 ;;
    esac
done

# Set default values if no arguments provided
if [ -z "$SCREENS_JSON_FILE" ]; then
    SCREENS_JSON_FILE="$PROJECT_ROOT/Packages/Sources/MyToyboxScreens/Resources/Screens.json"
fi

if [ -z "$SCREEN_ID_FILE" ]; then
    SCREEN_ID_FILE="$PROJECT_ROOT/Packages/Sources/MyToyboxScreens/Generated/Screen.swift"
fi

# Extract ids from Screens.json (now a simple string array)
# JSON format: ["id1", "id2", ...]
IDS=$(grep -o '"[^"]*"' "$SCREENS_JSON_FILE" | sed 's/"//g' | grep -v '^$')

# Validate that each id can be used as a Swift enum case name.
# - Must be a valid Swift identifier: ^[a-zA-Z_][a-zA-Z0-9_]*$
validate_identifier() {
    local id="$1"

    if [[ ! "$id" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
        echo "❌ Error: Invalid screen id for Swift identifier: \"$id\"" >&2
        echo "   - id must match: ^[a-zA-Z_][a-zA-Z0-9_]*$" >&2
        echo "   - example: gameOfLifeScreen, appleLogoScreen" >&2
        exit 1
    fi
}

# Generate case declarations
CASES=""
while IFS= read -r id; do
    validate_identifier "$id"
    CASES="${CASES}    case ${id}\n"
done <<< "$IDS"

# Remove the trailing newline
CASES=$(echo -e "$CASES" | sed '$ s/\\n$//')

# Create output directory
mkdir -p "$(dirname "$SCREEN_ID_FILE")"

# Generate Screen.swift
cat > "$SCREEN_ID_FILE" << 'HEADER'
// ⚠️ This file is auto-generated. Do not edit this file directly.
//
// Generated by: Scripts/generate_screen_id.sh
// Data source: Packages/Sources/MyToyboxScreens/Resources/Screens.json
//
import MetadatasMacros
import ScreenMacros
import SwiftUI

extension Screen: Identifiable {
    var id: String {
        rawValue
    }
}

// MARK: - Screen

/// Enum that identifies each sample screen.
///
/// ## Overview
///
/// This file is **auto-generated** by an SPM Build Tool Plugin during the build process.
/// You should not edit this file directly. Instead, modify the source data.
///
/// ## Generation Process
///
/// 1. **Input**: `Packages/Sources/MyToyboxScreens/Resources/Screens.json`
///    - Contains an array of screen IDs (string array)
/// 2. **Plugin**: `Packages/Plugins/GenerateScreenID/plugin.swift`
///    - SPM Build Tool Plugin that triggers generation
/// 3. **Script**: `Scripts/generate_screen_id.sh`
///    - Reads JSON, validates IDs, generates this Swift file
/// 4. **Output**: This file (`.build/plugins/outputs/.../Screen.swift`)
///    - SPM automatically includes plugin outputs in compilation
///
/// ## How It Works
///
/// The `@Screens` macro from [ScreenMacros](https://github.com/Koshimizu-Takehito/ScreenMacros)
/// generates `View` conformance. The `@Metadatas` macro generates `ScreenMetadata` conformance,
/// providing access to `title`, `description`, and `tags` properties.
///
/// Each case name is converted to UpperCamelCase and instantiated as the corresponding View type.
///
/// ```swift
/// case gameOfLifeScreen  →  GameOfLifeScreen()
/// case flowDistortionScreen  →  FlowDistortionScreen()
/// ```
///
/// ## Adding a New Screen
///
/// 1. Add a new entry to `Screens.json` with a unique `id`
/// 2. Create a corresponding View in `Packages/Sources/MyToyboxScreens/Screens/`
/// 3. Build the project - this file regenerates automatically
///
@Metadatas
@Screens
enum Screen: String, Codable, CaseIterable, Sendable {
HEADER

# Append cases
echo -e "$CASES" >> "$SCREEN_ID_FILE"

# Append closing brace
echo "}" >> "$SCREEN_ID_FILE"

# Append custom Codable implementation for string array decoding
cat >> "$SCREEN_ID_FILE" << 'FOOTER'

// MARK: - Codable Implementation

extension Screen {
    /// Custom decoder that decodes from a string array format.
    ///
    /// This allows `Screen` to be decoded directly from JSON arrays like:
    /// ```json
    /// ["gameOfLifeScreen", "mosaicScreen", ...]
    /// ```
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        
        guard let screen = Screen(rawValue: rawValue) else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Invalid screen ID: \(rawValue)"
            )
        }
        
        self = screen
    }
    
    /// Custom encoder that encodes to a string.
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
FOOTER

# Print result
SCREEN_COUNT=$(echo "$IDS" | wc -l | tr -d ' ')
echo "✅ Generated Screen.swift ($SCREEN_COUNT screens)"
echo "   Source: $(basename "$SCREENS_JSON_FILE")"
echo "   Output: $SCREEN_ID_FILE"
